export const BASE_URL = "https://mern-store-6dt0.onrender.com"
export const USERS_URL = "https://mern-store-6dt0.onrender.com/api/users"
export const CATEGORY_URL = "https://mern-store-6dt0.onrender.com/api/category"
export const PRODUCT_URL = "https://mern-store-6dt0.onrender.com/api/products"
export const UPLOAD_URL = "https://mern-store-6dt0.onrender.com/api/upload"
export const ORDERS_URL = "https://mern-store-6dt0.onrender.com/api/orders"
export const PAYPAL_URL = "https://mern-store-6dt0.onrender.com/api/config/paypal"