export const BASE_URL = "https://mern-e-commerce-api-dun.vercel.app"
export const USERS_URL = "https://mern-e-commerce-api-dun.vercel.app/api/users"
export const CATEGORY_URL = "https://mern-e-commerce-api-dun.vercel.app/api/category"
export const PRODUCT_URL = "https://mern-e-commerce-api-dun.vercel.app/api/products"
export const UPLOAD_URL = "https://mern-e-commerce-api-dun.vercel.app/api/upload"
export const ORDERS_URL = "https://mern-e-commerce-api-dun.vercel.app/api/orders"
export const PAYPAL_URL = "https://mern-e-commerce-api-dun.vercel.app/api/config/paypal"